title: MXK Software Craftmanship
email: mxksolutions@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Software craftmanship solutions covering various areas of Development,
  Architecture, Testing, Extreme Programming, Agile and DevOps.
# baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://m-x-k.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  m-x-k
locale: "en-gb"

# Build settings
markdown: kramdown
# theme: minimal-mistakes-jekyll
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dark"
repository: "m-x-k/m-x-k.github.io"

defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

analytics:
  provider: "google-universal"
  google:
    tracking_id: "UA-111584934-1"

related: true
breadcrumbs: true
search: true
permalink: /:categories/:title/
category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# Pagination Settings
pagination:
  enabled: true
  per_page: 3
  title: 'Posts - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
paginate_path: "/recent-posts/page:num"

author:
  name             : "Martin Kelly"
  avatar           : "assets/images/Avatars4.png"
  bio              : "Software developer"
  location         : "Edinburgh"
  email            : "mxksolutions@gmail.com"
  uri              :
  home             : http://mxk.solutions
  codepen          : mxk
  github           : m-x-k
  linkedin         : mxk-solutions
  slack            : mxksolutions.slack.com

include:
  - .htaccess
  - _pages
  - .nojekyll
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
